Repository pagopa/pagopa-gpd-rtp, pull requests merged in 2025-06, with the labels that each got.

#12 fix: Anonymizer url in UAT
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/gpd/rtp/service/impl/IngestionServiceImpl.java
Labels: size/small, patch

#15 feat: [PAGOPA-3121] Add isPartialPayment to RTPMessage
  src/main/java/it/gov/pagopa/gpd/rtp/events/model/PaymentOptionEvent.java
  src/main/java/it/gov/pagopa/gpd/rtp/events/model/RTPMessage.java
  src/main/java/it/gov/pagopa/gpd/rtp/service/impl/IngestionServiceImpl.java
  src/test/java/it/gov/pagopa/gpd/rtp/service/impl/IngestionServiceImplTest.java
Labels: minor

#14 Consumer
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/04_apim_api.tf
  infra/99_locals.tf
  infra/99_main.tf
  infra/99_variables.tf
  infra/env/weu-dev/terraform.tfvars
  infra/env/weu-prod/terraform.tfvars
  infra/env/weu-uat/terraform.tfvars
  infra/terraform.sh
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/gpd/rtp/GracefulShutdownHandler.java
  src/main/java/it/gov/pagopa/gpd/rtp/client/impl/RtpMilClientService.java
  src/main/java/it/gov/pagopa/gpd/rtp/config/CacheConfig.java
  src/main/java/it/gov/pagopa/gpd/rtp/config/RestTemplateConfig.java
  src/main/java/it/gov/pagopa/gpd/rtp/controller/EventsController.java
  src/main/java/it/gov/pagopa/gpd/rtp/controller/KafkaConsumerController.java
  src/main/java/it/gov/pagopa/gpd/rtp/events/broadcast/RedisPublisher.java
  src/main/java/it/gov/pagopa/gpd/rtp/events/broadcast/RedisSubscriber.java
  src/main/java/it/gov/pagopa/gpd/rtp/events/consumer/PaymentOptionConsumerConfig.java
  src/main/java/it/gov/pagopa/gpd/rtp/events/consumer/ProcessingTracker.java
  src/main/java/it/gov/pagopa/gpd/rtp/events/model/PaymentOptionEvent.java
  src/main/java/it/gov/pagopa/gpd/rtp/events/model/RTPMessage.java
  src/main/java/it/gov/pagopa/gpd/rtp/model/EventEnum.java
  src/main/java/it/gov/pagopa/gpd/rtp/repository/RedisCacheRepository.java
  src/main/java/it/gov/pagopa/gpd/rtp/service/impl/DeadLetterServiceImpl.java
  src/main/java/it/gov/pagopa/gpd/rtp/service/impl/FilterServiceImpl.java
  src/main/java/it/gov/pagopa/gpd/rtp/service/impl/IngestionServiceImpl.java
  src/main/java/it/gov/pagopa/gpd/rtp/service/impl/KafkaConsumerService.java
  src/main/java/it/gov/pagopa/gpd/rtp/service/impl/OptinServiceImpl.java
  src/main/java/it/gov/pagopa/gpd/rtp/util/Constants.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/gpd/rtp/GracefulShutdownHandlerTest.java
  src/test/java/it/gov/pagopa/gpd/rtp/controller/EventsControllerTest.java
  src/test/java/it/gov/pagopa/gpd/rtp/controller/KafkaConsumerControllerTest.java
  src/test/java/it/gov/pagopa/gpd/rtp/events/broadcast/RedisPublisherTest.java
  src/test/java/it/gov/pagopa/gpd/rtp/events/broadcast/RedisSubscriberTest.java
  src/test/java/it/gov/pagopa/gpd/rtp/repository/RedisCacheRepositoryTest.java
  src/test/java/it/gov/pagopa/gpd/rtp/service/impl/DeadLetterServiceImplTest.java
  src/test/java/it/gov/pagopa/gpd/rtp/service/impl/FilterServiceImplTest.java
  src/test/java/it/gov/pagopa/gpd/rtp/service/impl/IngestionServiceImplTest.java
  src/test/java/it/gov/pagopa/gpd/rtp/service/impl/KafkaConsumerServiceTest.java
  src/test/java/it/gov/pagopa/gpd/rtp/service/impl/OptinServiceImplTest.java
  src/test/resources/application.properties
Labels: size/large, minor

#18 private EH
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch

#20 feat(RedisCacheRepository.java): add retry logic for failed messages
  .devops/performance-test-pipelines.yml
  .github/workflows/cd_release_deploy.yml
  .identity/00_data.tf
  .identity/01_github_environment.tf
  Dockerfile
  docker/run_docker.sh
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/99_locals.tf
  infra/policy/_base_policy.xml
  openapi/openapi.json
  pom.xml
  postman-collection/README.md
  postman-collection/run_newman.sh
  sops.sh
  src/main/java/it/gov/pagopa/gpd/rtp/config/AppInsightsConfig.java
  src/main/java/it/gov/pagopa/gpd/rtp/config/OpenApiConfig.java
  src/main/java/it/gov/pagopa/gpd/rtp/controller/EventsController.java
  src/main/java/it/gov/pagopa/gpd/rtp/repository/RedisCacheRepository.java
  src/main/java/it/gov/pagopa/gpd/rtp/service/impl/DeadLetterServiceImpl.java
  src/main/java/it/gov/pagopa/gpd/rtp/service/impl/FilterServiceImpl.java
  src/main/java/it/gov/pagopa/gpd/rtp/service/impl/IngestionServiceImpl.java
  src/main/java/it/gov/pagopa/gpd/rtp/util/Constants.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
  src/test/java/it/gov/pagopa/gpd/rtp/MockConfig.java
  src/test/java/it/gov/pagopa/gpd/rtp/repository/RedisCacheRepositoryTest.java
  src/test/java/it/gov/pagopa/gpd/rtp/service/impl/DeadLetterServiceImplTest.java
  src/test/java/it/gov/pagopa/gpd/rtp/service/impl/FilterServiceImplTest.java
  src/test/java/it/gov/pagopa/gpd/rtp/service/impl/IngestionServiceImplTest.java
  src/test/resources/application.properties
Labels: size/large, patch

#22 fix elastic agent
  Dockerfile
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: size/small, patch
